apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: curs-valutar-autoupdate
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: prod
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@example.com
      messageTemplate: "chore: promote curs-valutar-app to {{ .UpdatedImage }}"
  update:
    path: infrastructure/k8s/overlays/prod
    strategy: Setters

