apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: curs-flask-dev-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: curs-flask-repo
  filterTags:
    pattern: '^dev-.*$'
  policy:
    alphabetical:
      order: asc
