apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: curs-valutar-dev-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: curs-valutar-repo
  filterTags:
    pattern: '^dev-.*'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
