apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: curs-valutar-prod-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: curs-valutar-repo
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$0'
  policy:
    alphabetical:
      order: asc

