gitleaks: 8.16.1
kubectl: 1.32.3
flux: 2.6.4
helm: 3.18.4
kustomize: 5.7.1
kubeconform: 0.6.4
kyvernoChart: 3.2.7
kyvernoApp: 1.12.4
yq: 4.43.1
trivy: 0.73.0
traefikApp: 3.5.0
traefikChart: 37.0.0
externalSecretsChart: 0.9.8
TRIVY_CACHE_DIR: /tmp/trivy-cache
HELM_PLUGIN_DIR: ~/.local/share/helm/plugins
KUBECTL_CONTEXT: remote-cloudflare

checkov: 3.3.13
yamllint: 1.38.0
argocdApp: 3.5.0
certManagerApp: 1.20.3
