gitleaks: v8.16.1
kubectl: v1.32.3
flux: v2.6.4
helm: 3.18.4
kustomize: v5.7.1
kubeconform: v0.6.4
kyverno: v1.12.4
yq: v4.43.1
trivy: 0.50.1
traefikApp: v3.5.0
traefikChart: 37.0.0
TRIVY_CACHE_DIR: /tmp/trivy-cache
HELM_PLUGIN_DIR: ~/.local/share/helm/plugins
KUBECTL_CONTEXT: remote-cloudflare
