extends: default

ignore: |
  infrastructure/flux/flux-system/manifests/flux-system/gotk-components.yaml

rules:
  line-length:
    max: 201
  indentation:
    spaces: 2
  empty-lines:
    max: 2
  truthy: disable
  document-start: disable
