apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curs-flask-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - exchange.istartit.com
      secretName: curs-flask-tls
  rules:
    - host: exchange.istartit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: curs-flask
                port:
                  number: 80
