apiVersion: apps/v1
kind: Deployment
metadata:
  name: curs-flask
spec:
  template:
    spec:
      # Pod‑level hardening for dev
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true

      containers:
      - name: curs-flask
        image: trojanul2008/curs-flask:dev-latest

        # Container‑level hardening for dev
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true

        env:
        - name: FLASK_ENV
          value: "development"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"

