apiVersion: apps/v1
kind: Deployment
metadata:
  name: curs-flask
spec:
  template:
    spec:
      containers:
        - name: curs-flask
          image: trojanul2008/curs-flask:dev-latest
          env:
            - name: FLASK_ENV
              value: "development"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
