apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

images:
  - name: trojanul2008/curs-flask
    newName: trojanul2008/curs-flask
    newTag: dev-PLACEHOLDER

