apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: remove-affinity-patch.yaml
images:
  - name: trojanul2008/curs-valutar-app
    newName: trojanul2008/curs-valutar-app
    digest: sha256:8f10b4ed01392d3c10f6b07210fdf5f38684d72f698a49ed0b1260b425a32f75
