apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: remove-affinity-patch.yaml
images:
  - name: trojanul2008/curs-valutar-app
    newName: trojanul2008/curs-valutar-app
    digest: sha256:b528bcbcb1cf1f0a00a52b366ad694c2bcb3f4fc0bb560612e4979543e4fde98
