apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curs-valutar-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: ".;../../base"
spec:
  project: default
  source:
    repoURL: https://github.com/trojanul2008/curs-valutar-infra.git
    targetRevision: refs/heads/main
    path: infrastructure/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
