name: "Install kubectl"
description: "Installs kubectl CLI"
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x install.sh
        ./install.sh
      shell: bash
      working-directory: ${{ github.action_path }}
