apiVersion: apps/v1
kind: Deployment
metadata:
  name: curs-valutar
spec:
  selector:
    matchLabels:
      app: curs-valutar
  replicas: 2
  template:
    spec:
      imagePullSecrets:
        - name: docker-credentials
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: curs-valutar
          image: trojanul2008/curs-valutar-app:prod-latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop: ["ALL"]
          env:
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_APP
              value: "curs_valutar:create_app"
            - name: PYTHONPATH
              value: "/app"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "256Mi"
              cpu: "500m"
              ephemeral-storage: "200Mi"

