apiVersion: apps/v1
kind: Deployment
metadata:
  name: curs-flask
spec:
  replicas: 2
  template:
    spec:
      # Pod‑level hardening for prod
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true

      containers:
      - name: curs-flask
        image: trojanul2008/curs-flask:prod-latest

        # Container‑level hardening for prod
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true

        env:
        - name: FLASK_ENV
          value: "production"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"

