apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: remove-affinity-patch.yaml

images:
  - name: trojanul2008/curs-flask
    newName: trojanul2008/curs-flask
    # <-- This will be updated by Flux ImageUpdateAutomation to the exact semver, e.g. "v1.2.3"
    newTag: v0.0.0

