name: "Install kustomize"
description: "Installs kustomize using version from versions.yaml"

runs:
  using: "composite"
  steps:
    - name: Run kustomize installer
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/install.sh
        ${{ github.action_path }}/install.sh
