name: "🏷️ Auto Tag Release on Version Bump"
on:
  push:
    branches: [dev, prod]
    paths:
      - ".github/versions.yaml"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse version and tag
        id: tagger
        run: |
          VERSION=$(yq '.kubectl' .github/versions.yaml | tr -d '"')
          TAG="infra-${VERSION}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Create tag
        run: |
          git config --global user.name "GitOps"
          git config --global user.email "gitops@ci"
          git tag "${{ steps.tagger.outputs.tag }}"
          git push origin "${{ steps.tagger.outputs.tag }}"
