apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url:      ssh://git@github.com/trojanul2008/curs-valutar.git
  ref:
    branch: prod
  secretRef:
    name: flux-system

