apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: git@github.com:trojanul2008/curs-flask.git
  secretRef:
    name: flux-system
  webhook:
    # Configure GitHub webhook in repo settings pointing to Flux
    endpoint: /flux-webhook
    port: 9443
