apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- gotk-components.yaml
  - gotk-sync.yaml
  - manifests/source-dev.yaml         # ensures infra-dev GitRepository exists
  - manifests/dev-kustom.yaml         # creates the Kustomization that deploys dev
  # add prod equivalents if needed:
  - manifests/source-prod.yaml
  - manifests/prod-kustom.yaml
  # any other CRs you want Flux to manage:
  - manifests/image-repository.yaml
  - manifests/image-policy-dev.yaml
  - manifests/image-update-automation-dev.yaml
  - manifests/external-secrets-install.yaml
  - manifests/curs-valutar-dev.yaml
  - manifests/curs-valutar-prod.yaml
