 resources:
   - gotk-components.yaml
   - gotk-sync.yaml
   - app-kustomization.yaml

   # Flux Image Automation
   - image-repository.yaml
   - image-policy.yaml
   - image-update-automation.yaml
   - image-policy-dev.yaml
   - image-update-automation-dev.yaml

